name: Call-reusable-workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-workflow.yml 
    with:
      label: reusable-workflow-test
