name: Reusable workflow example

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string


jobs:
  printlabel:
    runs-on: ubuntu-latest
    steps:
    - id: print
      run: | 
         cat ${{ inputs.label }}
