name: Reusable workflow example

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string


jobs:
  printlabel:
    runs-on: ubuntu-latest
    steps:
    - id: print
      run: | 
         echo ${{ inputs.label }}
