name: scuccessful-workflow

on: 
  workflow_dispatch:
  
jobs:
  succesfuljob:
   runs-on: ubuntu-latest
   steps:
   - name: cat-readme
     uses: ./.github/workflows/reusable-workflow.yml 
     with:
      filename: ./README.md
