name: succesful-workflow

on: 
  workflow_dispatch:
  
jobs:
  name: cat-existing:
  steps:

    - name: Checkout repo
      uses: actions/checkout@v3
    - name: 
      uses: ./.github/workflows/reusable-workflow.yml 
      with:
        filename: ./README.md
