name: scuccessful-workflow

on: 
  workflow_dispatch:
  
jobs:
  succesfuljob:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v3 
   - id: call
     uses: ./.github/workflows/reusable-workflow.yml 
     with:
      filename: ./README.md
